name: Build & Publish Image to Docker Hub
on:
  # push:
  #   branches:
  #     - main
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_image
        run: docker build ./sdv-api -t qinismlinbiaoism/sdv-m1do-sdv-api:master
      - name: push_image
        run: |
          docker login -u qinismlinbiaoism -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push qinismlinbiaoism/sdv-m1do-sdv-api:master
