name: Build & Publish Image to Docker Hub
on:
  # push:
  #   branches:
  #     - main
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_image
        run: | 
          docker build ./sdv-api --target dev -t qinismlinbiaoism/sdv-api-dev:latest
          docker build ./sdv-api --target prod -t qinismlinbiaoism/sdv-api:latest
          docker build ./sdv-web --target dev -t qinismlinbiaoism/sdv-web-dev:latest
          docker build ./sdv-web --target prod -t qinismlinbiaoism/sdv-web:latest
      - name: push_image
        run: |
          docker login -u qinismlinbiaoism -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push qinismlinbiaoism/sdv-api:latest
          docker push qinismlinbiaoism/sdv-api-dev:latest
          docker push qinismlinbiaoism/sdv-web:latest
          docker push qinismlinbiaoism/sdv-web-dev:latest
